# Generated by Django 5.2.12 on 2026-03-26 01:49

import apps.product.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RICE', 'Arroz'), ('BEANS', 'Feijão')], max_length=10, verbose_name='Nome')),
                ('average_price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço médio por kg')),
            ],
            options={
                'verbose_name': 'categoria de produto',
                'verbose_name_plural': 'categorias de produtos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.product.utils.product_image_path, verbose_name='Imagem')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
