# Generated by Django 5.2.12 on 2026-03-21 01:42

import apps.home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.home.utils.product_image_path, verbose_name='Imagem')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
